<a href="https://colab.research.google.com/github/adrianciemerych/machine-learning/blob/main/ml_course/preprocessing/06_train_test_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns

np.random.seed(42)
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: f'{x:.2f}'))
sns.set()
sklearn.__version__

'1.2.2'

In [ ]:
# Załadowanie danych z gotowego źródła scikitlearn

from sklearn.datasets import load_iris


raw_data = load_iris()
raw_data_copy = raw_data.copy()
raw_data_copy.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
print(raw_data_copy['DESCR'])

In [ ]:
data = raw_data_copy['data']
target = raw_data_copy['target']

print(f'{data[:5]}\n')
print(target[:5])

[[5.10 3.50 1.40 0.20]
 [4.90 3.00 1.40 0.20]
 [4.70 3.20 1.30 0.20]
 [4.60 3.10 1.50 0.20]
 [5.00 3.60 1.40 0.20]]

[0 0 0 0 0]


In [ ]:
# Połączenie atrybutów ze zmienną docelową

all_data = np.c_[data, target]
all_data
df = pd.DataFrame(all_data, columns = raw_data_copy['feature_names'] + ['target'])
df.sample(20)

In [ ]:
df.head()
df.tail()
df.info()
df.describe()
df.describe().T.apply(lambda x: round(x, 2))
# df oznaczamy samą ramkę danych którą zajmujemy się do naszego modelu
# Zbadanie rozkładu zmiennej docelowej - zawierającej informacje o klasie kwiatka
df.target.value_counts()

0.0    50
1.0    50
2.0    50
Name: target, dtype: int64

In [ ]:
# Rozdzielanie danych opisujących i opisywanych
# dzięki metodzie pop można za jednym razem pozbyć się kolumny z df i przypisać
# ją do innej zmiennej
data  = df.copy()
data
target = data.pop('target')
data
target

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: target, Length: 150, dtype: float64

In [ ]:
# Tworzenie zbioru treningowego oraz zbioru testowego

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

print(f"X_train shape {X_train.shape}")
print(f"y_train shape {y_train.shape}")
print(f"X_test shape {X_test.shape}")
print(f"y test shape {y_test.shape}")
print(f"\nTest ratio: {len(X_test)/len(data):.2f}")
print(f"\ny_train:\n{y_train.value_counts()}")
print(f"\ny_test:\n{y_test.value_counts()}")

NameError: ignored

In [ ]:
# parametr test_size pozwala określić stosunek wartości testowych
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size = 0.3, random_state=42)

print(f"X_train shape {X_train.shape}")
print(f"y_train shape {y_train.shape}")
print(f"X_test shape {X_test.shape}")
print(f"y test shape {y_test.shape}")
print(f"\nTest ratio: {len(X_test)/len(data):.2f}")
print(f"\ny_train:\n{y_train.value_counts()}")
print(f"\ny_test:\n{y_test.value_counts()}")

In [ ]:
# parametr train_size pozwala określić stosunek wartości treningowych
X_train, X_test, y_train, y_test = train_test_split(data, target, train_size = 0.3, random_state=42)

print(f"X_train shape {X_train.shape}")
print(f"y_train shape {y_train.shape}")
print(f"X_test shape {X_test.shape}")
print(f"y test shape {y_test.shape}")
print(f"\nTest ratio: {len(X_test)/len(data):.2f}")
print(f"\ny_train:\n{y_train.value_counts()}")
print(f"\ny_test:\n{y_test.value_counts()}")

In [ ]:
# parametr stratify pozwala na równe rozłożenie danych np. docelowych,
# co jest zazwyczaj pożądane
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size = 0.1, random_state=42, stratify = target)

print(f"X_train shape {X_train.shape}")
print(f"y_train shape {y_train.shape}")
print(f"X_test shape {X_test.shape}")
print(f"y test shape {y_test.shape}")
print(f"\nTest ratio: {len(X_test)/len(data):.2f}")
print(f"\ny_train:\n{y_train.value_counts()}")
print(f"\ny_test:\n{y_test.value_counts()}")

Podział danych na zbiór treningowy i testowy - breast cancer data

In [ ]:
from sklearn.datasets import load_breast_cancer

raw_data = load_breast_cancer()
raw_data_copy = raw_data.copy()
raw_data_copy.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
print(raw_data_copy['DESCR'])

In [ ]:
len(raw_data_copy['feature_names'])
raw_data_copy['feature_names']
raw_data_copy['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
data = raw_data_copy['data']
target = raw_data_copy['target']
#print(data[0:5])
#print(target[0:5])

all_data = np.c_[data, target]
all_data[:5]

df = pd.DataFrame(all_data, columns = list(raw_data_copy['feature_names']) + ['target'])
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890     0.0  
1                  0.1860          0.2750                  0.08902     0.0  
2                  0.2430          0.3613                  0.08758     0.0  
3                  0.2575          0.6638                  0.17300     0.0  
4                  0.1625          0.2364                  0.076

In [ ]:
df.target.value_counts()

1.0    357
0.0    212
Name: target, dtype: int64

In [ ]:
data = df.copy()
target = data.pop('target')
data.head()
target.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: target, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size = 0.25, random_state=40)

print(f"X_train shape {X_train.shape}")
print(f"y_train shape {y_train.shape}")
print(f"X_test shape {X_test.shape}")
print(f"y test shape {y_test.shape}")
print(f"\nTest ratio: {len(X_test)/len(data):.2f}")
print(f"\ny_train:\n{y_train.value_counts()}")
print(f"\ny_test:\n{y_test.value_counts()}")


X_train shape (426, 30)
y_train shape (426,)
X_test shape (143, 30)
y test shape (143,)

Test ratio: 0.25

y_train:
1.0    259
0.0    167
Name: target, dtype: int64

y_test:
1.0    98
0.0    45
Name: target, dtype: int64


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size = 0.25, random_state=40, stratify = target)

print(f"X_train shape {X_train.shape}")
print(f"y_train shape {y_train.shape}")
print(f"X_test shape {X_test.shape}")
print(f"y test shape {y_test.shape}")
print(f"\nTest ratio: {len(X_test)/len(data):.2f}")
print(f"\ny_train:\n{y_train.value_counts()}")
print(f"\ny_test:\n{y_test.value_counts()}")

X_train shape (426, 30)
y_train shape (426,)
X_test shape (143, 30)
y test shape (143,)

Test ratio: 0.25

y_train:
1.0    267
0.0    159
Name: target, dtype: int64

y_test:
1.0    90
0.0    53
Name: target, dtype: int64
